site_name: IAM Blog
site_author: Mai Bui
site_description: >-
  My name is Mai Bui and I am currently working as a Software engineer. This blog is a place where I share my knowledges that I have learned and experienced. 
  Hope that you –  a stranger who have a lot of questions can find your answer here. Scroll down for more information about me.
theme:
  name: material
  custom_dir: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: lime
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light green
      accent:

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/bntmai911
    - icon: fontawesome/brands/wordpress
      link: https://jm119.wordpress.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thanh-mai-b%C3%B9i-ng%E1%BB%8Dc-9230b910b/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

copyright: |
  &copy; 2023 <a href="https://github.com/bntmai911/iamblog"  target="_blank" rel="noopener">Mai Bui</a>

nav:
  - Home: index.md
  - BE:
      - Camunda Optimistic Locking: BE/CamundaOptimisticLocking.md
  - FE:
      - Angular Reactive form common mistakes: FE/ReactiveFormMistakes.md
  - DevOps:
      - Docker tutorial Angular + Spring boot application: DevOps/AngularSpringBootDocker.md
  - Work's note:
      - Regex Validation: Others/RegexEmailValidation.md
  - Travel:
      - Home: Travel/introduction.md
  - Languages:
      - Home: Languages/introduction.md
